### ISSUE TITLE
COMPUERTAS LOGICAS

### ISSUE THREAD

**Issue by RicardoMtzSts** [SistemasTecTlaxiaco/compuertas-logicas-equipo-saul-lopez-bautista#1]
[Practica Compuertas logicas .pdf](https://github.com/SistemasTecTlaxiaco/compuertas-logicas-equipo-saul-lopez-bautista/files/7724625/Practica.Compuertas.logicas.pdf)

**Comment by Julissamigdalia** [comment]
El trabajo está bien, solo faltó la descripción de las figuras. 19/20

**Comment by Julissamigdalia** [comment]
El trabajo está bien,solo faltó la descripción de las figuras
29/30

**Comment by josealfredo79** [comment]
Bien hecho y revisado
